{"uuid": "bbe7fe2c-9b3f-4029-8624-eaee962a9758", "children": ["8d02c76f-e3c8-4dc2-9e68-ba8cea38fc28", "ea06406b-53e5-4559-88c9-5bc813325e57", "d6c8898e-88d5-426d-803b-e01114bea1ea", "f64c383b-bbd0-4d8d-851f-ec98cddad56f", "388c8af4-9e4b-4f47-9254-ef77729bf0fc", "857e389c-a866-4780-90a1-5385a8c8c3dd", "65fbff44-f63d-4110-bbfe-782848697a76", "736857c8-960d-4d9c-a019-9535b8be24df", "bf9c86bc-2193-4310-838b-343dbfaf83b6", "0f90eb32-8f72-4189-8070-95d29f9a12eb"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"c:\\users\\ikozh\\gi_test\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\ikozh\\gi_test\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\ikozh\\gi_test\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\ikozh\\gi_test\\tests\\conftest.py\", line 7, in browser\n    driver = webdriver.Chrome(executable_path=\"./chromedriver\")\n  File \"c:\\users\\ikozh\\gi_test\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"c:\\users\\ikozh\\gi_test\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1622836542826, "stop": 1622836542839}], "start": 1622836542826, "stop": 1622836543138}